# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: gh:seedcase-project/template-rs
copyright_year: '2026'
for_seedcase: true
github_repo: zen-do
github_user: seedcase-project
hosting_provider: netlify
