project:
  type: seedcase-theme

website:
  title: "zen-do"
  site-url: "https://zen-do.seedcase-project.org"
  repo-url: "https://github.com/seedcase-project/zen-do"
  page-navigation: true
  navbar:
    pinned: true
    title: false
    logo: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
    logo-alt: "Seedcase logo: Main page"
    left:
      - text: "Overview"
        href: docs/index.qmd
      - text: "Guide"
        href: docs/guide/index.qmd
      - text: "Design"
        href: docs/design/index.qmd
      # - text: "Reference"
      #   href: docs/reference/index.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/zen-do"
        aria-label: "GitHub icon: Source code"
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Main website for the Seedcase Project"
  sidebar:
    - id: overview
      pinned: true
      style: "floating"
      contents:
        - docs/index.qmd
        - CHANGELOG.qmd
        - CONTRIBUTING.md
    - id: design
      contents:
        - text: "Design"
          href: docs/design/index.qmd
        - docs/design/architecture.qmd
        - section: "Interface"
          href: docs/design/interface/index.qmd
          contents:
            - docs/design/interface/inputs.qmd
            - docs/design/interface/outputs.qmd
            - docs/design/interface/cli.qmd
    - id: guide
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd

# quartodoc:
#   sidebar: "docs/reference/_sidebar.yml"
#   style: "pkgdown"
#   dir: "docs/reference"
#   package: "zen_do"
#   parser: google
#   dynamic: true
#   renderer:
#     style: _renderer.py
#     table_style: description-list
#     show_signature_annotations: true

# metadata-files:
#   - docs/reference/_sidebar.yml

format:
  seedcase-theme-html:
    include-before-body:
      - "docs/includes/site-counter.html"
